### ISSUE TITLE
Mention to disable Secure Boot in docs

### ISSUE THREAD

**Issue by cassidyjames** [pop-os/docs#104]
Apparently Secure Boot isn't supported according to @jackpot51, which I can't find a mention of anywhere. I tried installing the new 20.04 release but it failed and I ended up giving up—but apparently the issue may have been that my machine has Secure Boot on.

Considering Ubuntu, elementary OS, Fedora, and more work ootb with Secure Boot these days, it was not obvious to me that it could be causing any issues.

**Comment by jackpot51** [comment]
This has been added to the download page
> Disable Secure Boot in your BIOS to install Pop!_OS.
