### ISSUE TITLE
Installation walkthrough using Etcher

### ISSUE THREAD

**Issue by jackpot51** [pop-os/docs#30]
Show how to flash the ISO to a USB stick, and install it on a computer. Link this in a prominent place on https://system76.com/pop

**Comment by ahoneybun** [comment]
There is a link to this:
http://pop.system76.com/docs/install-pop-os/ 

on the download page, is that good?

**Comment by dragonbite** [comment]
May want to add how big of a USB stick is necessary.  I think 4GB is adequate currently, but some people may try grabbing any old stick and not know how big it is offhand.  Will it install using a 2GB stick?

**Comment by macharyas** [comment]
After installing Etcher 1.3.1 AppImage on Pop!_OS 17.10, it would not launch to create a bootable drive for 18.04. To enable Etcher to launch I found (on GitHub) that I had to run the following command from the Terminal: 

sudo add-apt-repository universe && sudo apt-get update && sudo apt-get install -y libgconf-2-4

After which, it launched immediately and I was able to complete the process of making the drive.

**Comment by ahoneybun** [comment]
Interesting. Did you have this issue with Pop!_OS 18.04?

**Comment by brs17** [comment]
@jackpot51 I believe this can be closed as we have `Install Instructions` linked under the "Download" popup, and we link etcher instructions in there.

Note: The page could be updated to resemble 18.04, but that is another issue entirely.
