### ISSUE TITLE
Translation to commonly used famous apps

### ISSUE THREAD

**Issue by uchuugaka** [pop-os/docs#41]
This use of Super is a little different and new. 
Emacs is where Super once was a true key along with dozens of others like Meta and Hyper.
How do these kb shortcuts translate to Emacs?
Vim?
Terminal?
Defaults before user customization.

**Comment by sramkrishna** [comment]
I think it depends.  In the old days, emacs would use a control character or esc-character for meta.  With versions of linux, meta was the alt key, and super was the windows key.  There is some overlap, so you will need to either config emacs to use other keyboard shortcuts or change GNOME's.  With VIM there is no conflict that I am aware of.  I'm not an emacs user.  I did some searching, and you could look at this:

https://askubuntu.com/questions/30224/how-to-disable-the-alt-hotkey-behavior-on-gnome-terminal
https://unix.stackexchange.com/questions/21356/gnome-stop-grabbing-my-emacs-keys
