### ISSUE TITLE
Some Shortcuts Not Working

### ISSUE THREAD

**Issue by jmd1011** [pop-os/docs#45]
Upon a fresh install, many shortcuts aren't working for me:

- Shift + Ctrl + Super + [direction]: none working
- Almost none of the OS shortcuts work (only Super, Super + A, Super + V,  and Alt + F2 work)
- Super + M is performing the same thing as Super + V

Also, just a small thing -- it would be nice to be able to directly switch to a specific workspace (Super + 4, etc.).

**Comment by jmd1011** [comment]
After a reboot, both Super + P and Shift + Ctrl + Super + [direction] work, but the other issues remain.

**Comment by brs17** [comment]
@jmd1011 thank you for submitting this issue. 

A very similar issue was created a couple of days ago https://github.com/pop-os/pop/issues/171 and I have replied there. Going to close this issue as it is a duplicate.
