### ISSUE TITLE
pop-live-disk.md not displaying popsicle.png and others

### ISSUE THREAD

**Issue by PatrickDGarvey** [pop-os/docs#58]
**Distribution (run `cat /etc/os-release`):**
 Create and Use Bootable Media on Pop!_OS web page
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**
https://pop.system76.com/docs/pop-live-disk/

**Issue/Bug Description:**
pop-live-disk.md not displaying popsicle.png and others

**Steps to reproduce (if you know):**
Open URL https://pop.system76.com/docs/pop-live-disk/ in any browser.

**Expected behavior:**
Find and display referenced .png files.

**Other Notes:**

**Comment by cassidyjames** [comment]
The images are absolute, but need to be relative/use the Jekyll site root.

**Comment by ahoneybun** [comment]
Should be fixed with commit:

https://github.com/pop-os/docs/commit/de982d942c1927d4f62248ffc5cea733892a4001

**Comment by ahoneybun** [comment]
Looks fixed. Please confirm @cassidyjames @PatrickDGarvey

**Comment by cassidyjames** [comment]
@ahoneybun see https://github.com/system76/docs#images--links for the image link format.

**Comment by cassidyjames** [comment]
@ahoneybun ah that seems to have fixed it. It helps to include the images, huh? :smile: It's still best practice to use `{{ site.baseurl }}` in case the docs ever move, but I can consider this fixed now.

**Comment by PatrickDGarvey** [comment]
I concur, the page is now displaying .png images.
