### ISSUE TITLE
Run-on sentences

### ISSUE THREAD

**Issue by dandv** [pop-os/docs#63]
Hi, don't mean to ruffle any feathers and no, I'm not a grammar nazi :) Just wanted to relay feedback on an issue with the style of the docs. On the [live-disk](https://pop.system76.com/docs/pop-live-disk/) help page, there are a bunch of run-on sentences that just... not sure how to say this better, didn't inspire trust in Pop!_OS. I've just discovered Pop!_OS today, and wanted to give it a try.

Not all occurrences of run-on sentenced felt jarring, only a few:

> In order to install Pop!_OS, first download the .iso image, this is a disk image with the operating system and installer on it.

> Popsicle is an open source app for Linux that allows you to “burn images to USB drives safely and easily”, it is installed in Pop!_OS 18.04 and up.

etc.

Anyway, just thought this might have been an oversight, but if it's ok with the style guide of the docs, please don't mind me and feel free to close the issue :)

**Comment by lmanalas** [comment]
Thank you for bringing this to our attention. We'll go through the docs and proofread them.

**Comment by brs17** [comment]
@dandv feel free to create PRs with changes as you see fit! :D

**Comment by Socialhappiness** [comment]
I've updated the article, thanks for the feedback! https://github.com/pop-os/docs/pull/65/commits

**Comment by dandv** [comment]
Thanks for the update! Hope to see it pushed live, because https://support.system76.com/articles/live-disk/ still refers to Etcher instead of Popsicle.

BTW, any plans for making the ISO writable by the official [Startup Disk Creator](https://en.wikipedia.org/wiki/Startup_Disk_Creator)?

**Comment by ahoneybun** [comment]
That page will be Etcher forever while this page is for Popsicle:
https://support.system76.com/articles/pop-live-disk/

The Startup Disk Creator has issues and I don't recommend using it at all.

**Comment by dandv** [comment]
I see. Where can I learn more about the issues with Startup Disc Creator? I've been using it for 5+ year without problems, until now when I couldn't burn the Pop ISO.

I've used Etcher, but the image doesn't boot:

![20181214_234657](https://user-images.githubusercontent.com/33569/50040581-01fc8280-fffb-11e8-9511-d3b415586cc5.jpg)

**Comment by dandv** [comment]
Any updates on this? Combined with the new issue I've just filed, I've basically been unable to install Pop!_OS. Am I the only one, missing some non-obvious method to get this ISO booting?

**Comment by ahoneybun** [comment]
I would check the sha256sum of the image as something is wrong with the image used. Is this the 18.04 or 18.10 image?

**Comment by dandv** [comment]
It's the 18.04 LTS image. Since this isn't a docs issue, I've filed a separate one, and noted the SHA sum.

https://github.com/pop-os/iso/issues/225
