### ISSUE TITLE
Download link for 19.04 Nvidia not working

### ISSUE THREAD

**Issue by sachincool** [pop-os/docs#76]
Hey guys, Awesome Development work! 
I just wanted you guys to know that PopOS ISO  19.04 for nvidia  Download link is not working and leading to a non-existent bucket. [here](https://pop-iso.sfo2.cdn.digitaloceanspaces.com/19.04/amd64/nvidia/3/pop-os_19.04_amd64_nvidia_3.iso)

also I researched and found this bucket listing here https://pop-iso.sfo2.cdn.digitaloceanspaces.com/ 

I didn't knew where to contact. I hope it helps you guys 😄 👍

**Comment by jackpot51** [comment]
Where are you located?

We distribute the ISO using the DigitalOcean CDN. We have confirmed the ability to download in the US, but CDNs take some time to sync to all the end nodes.

If I know roughly where you are located, I can check if it has synced to that location, or if perhaps this is a caching issue.

**Comment by sachincool** [comment]
LOL!!  
I'm from India. 
I just tried to access the same link via US vpn and it worked like a charm. But still gives me "No-Such Key" S3 error when I try to access it from `Bangalore, India`. 
I didn't knew DO cdn uses s3 internally.

**Comment by btkostner** [comment]
@sachincool It seems DO was having issues with one of the regions when we launched the new ISO. That caused the `No-Such Key` error. We recently purged the whole CDN and everything seems to have synced correctly. Can you confirm this works for you without a VPN?

**Comment by sachincool** [comment]
Works!! :+1: closing this issue, ty for the help.
