### ISSUE TITLE
Links on pop-live-disk.md 404

### ISSUE THREAD

**Issue by WereDev** [pop-os/docs#84]
Links on the top of the pop-live-disk page (pop-live-disk.md) 404 when clicking on them:
- Installing Pop!_OS
- Determining if an issue is caused by hardware or software
- Fixing the boot loader

**Comment by brs17** [comment]
Can you try again? Currently I am unable to recreate your issue (the links work just fine for me).

**Comment by WereDev** [comment]
I think I may have stumbled across an old version of the docs?

Links on this page work:
https://support.system76.com/articles/pop-live-disk/

Links on this page don't work:
https://pop.system76.com/docs/pop-live-disk/

**Comment by mokshchaudhary** [comment]
Done #88
